### ISSUE TITLE
Import doesn't work, gives error.

### ISSUE THREAD

**Issue by JamesO2x** [ldo/blender_pycollada_importexport#2]
I was able to export a mesh to DAE, but was not able to import it using this pycollada add-on. The error I get on import is:

```
Time to load .dae file = 0.03s
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender_pycollada_importexport-master\__init__.py", line 109, in execute
    return import_collada.load(self, context, self.filepath.endswith(".zae"), **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender_pycollada_importexport-master\import_collada.py", line 1205, in load
    importer = get_import(c)(ctx, c, filepath, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender_pycollada_importexport-master\import_collada.py", line 56, in __init__
    self.DAE_NS = {"dae": collada.xmlnode.getroot().nsmap[None]}
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'nsmap'

location: <unknown location>:-1
```

The default Collada import was able to import the mesh.

---

Also, is this add-on still being developed? I only recently learned of the weird C++ situation of the default Blender Collada importer/exporter. I wanted to improve the vertex alpha import on it, and found out that the default Collada I/O module for Blender wasn't built with python, and has to be compiled into the Blender program.

I was looking for an alternative python Collada importer/exporter and stumbled upon this one.

**Comment by ldo** [comment]
I just checked it, and I think the error is occurring because your system only has `xml.etree` from the standard Python library, whereas this addon is relying on features specific to [`lxml`](https://lxml.de/api.html#lxml-etree). Pycollada should use the latter if available -- at least on Debian it does.

**Comment by JamesO2x** [comment]
Ok, I'll try it out later. When I installed this add-on I initially got errors for missing module "collada" -- I fixed that by installing PyCollada through pip. Simple fix. But then I ran into this error.

Other than `pycollada` and `lxml`, are there any other dependencies this add-on needs?

I'm not a python pro by any means, so I don't know what modules are or are not installed by default in the standard library, or on different OS/systems, or Blender's own Python default install on different systems.

If you have a list of any other possible "hidden dependencies" that would help me out a lot. I can find most of the needed modules by just looking at the different `import` lines in this add-on's code, but the term `lxml` didn't show up when I searched the repo, so I wouldn't have known I needed that one if you hadn't mentioned it.

**Comment by JamesO2x** [comment]
Well I just installed `lxml` and confirmed that it installed correctly, but I still get this same error in Blender with this addon. Not sure what to do. I'm running Blender 3.1 on Windows 10, not sure if that info helps or not.

**Comment by ldo** [comment]
Can your pycollada find it, though?

**Comment by JamesO2x** [comment]
I don't see why it wouldn't be able to find it. I installed both with PIP in the same exact way. And if I run Python.exe out of the Blender directory from command line, I can `import` both `lxml` and `pycollada` just fine, and verify they're both working by checking the `-help` command.

I don't know enough about pycollada to know what its doing internally to choose whether to use `xml` or `lxml`. But when installing `pycollada` with PIP, it did install a few dependencies, but `lxml` wasn't one of them. I had to install that manually after. Maybe this add-on is using a specific older version of `pycollada` and the default version installed from PIP today has incompatible changes?

**Comment by ldo** [comment]
You can check that lxml is accessible from Blender python code (including pycollada) quite easily. In Blender’s Python console, type

     from collada import schema

which should complete without error. For added value, try

     schema.lxml

which should display something like

    <module 'lxml' from '/usr/lib/python3/dist-packages/lxml/__init__.py'>

**Comment by ldo** [comment]
No further activity.
