### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ghost** [ldo/blender_pycollada_importexport#3]
Hi

I use Blender 3.4.1 on Windows
How to install this add-on in Blender, step by step please?

**Comment by ldo** [comment]
I don’t recommend trying this on Microsoft Windows. See #2 for some of the trouble you are likely to encounter.

For reference: https://docs.blender.org/manual/en/latest/editors/preferences/addons.html

**Comment by ghost** [comment]
How can a Blender add-on behave differently on Windows then on the system you use?
Blender and python are cross platform and shouldn't an add-on do the same on each OS?

Can you fix it or is it not possible? I want to test it on Windows!
I don't understand the reason why.

Is it correct Blender's collada import is full of bugs? I'm not able to import 1 model correctly, because there is always something missing or wrong (texture, color, model part)

**Comment by ghost** [comment]
Can you tell me the way to install it on windows?
Or is this just not possible?

**Comment by ghost** [comment]
Please don't close this issue. It's very important because it does not work on windows.
Blender add-ons should be cross-platform.

Can you fix your code so it works on all platform Blender runs on?
Otherwise it doesn't make much sense to make an add-on that only runs on some OSes on which Blender runs...
What exactly is the problem?
